export const parentsData = [
    {
      id: 1,
      name: "John Doe",
      students: ["Sarah Brewer"],
      email: "john@doe.com",
      phone: "1234567890",
      address: "123 Main St, Anytown, USA",
    },
    {
      id: 2,
      name: "Jane Doe",
      students: ["Cecilia Bradley"],
      email: "jane@doe.com",
      phone: "1234567890",
      address: "123 Main St, Anytown, USA",
    },
    {
      id: 3,
      name: "Mike Geller",
      students: ["Fanny Caldwell"],
      email: "mike@geller.com",
      phone: "1234567890",
      address: "123 Main St, Anytown, USA",
    },
    {
      id: 4,
      name: "Jay French",
      students: ["Mollie Fitzgerald", "Ian Bryant"],
      email: "mike@geller.com",
      phone: "1234567890",
      address: "123 Main St, Anytown, USA",
    },
    {
      id: 5,
      name: "Jane Smith",
      students: ["Mable Harvey"],
      email: "mike@geller.com",
      phone: "1234567890",
      address: "123 Main St, Anytown, USA",
    },
    {
      id: 6,
      name: "Anna Santiago",
      students: ["Joel Lambert"],
      email: "mike@geller.com",
      phone: "1234567890",
      address: "123 Main St, Anytown, USA",
    },
    {
      id: 7,
      name: "Allen Black",
      students: ["Carrie Tucker", "Lilly Underwood"],
      email: "mike@geller.com",
      phone: "1234567890",
      address: "123 Main St, Anytown, USA",
    },
    {
      id: 8,
      name: "Ophelia Castro",
      students: ["Alexander Blair"],
      email: "mike@geller.com",
      phone: "1234567890",
      address: "123 Main St, Anytown, USA",
    },
    {
      id: 9,
      name: "Derek Briggs",
      students: ["Susan Webster", "Maude Stone"],
      email: "mike@geller.com",
      phone: "1234567890",
      address: "123 Main St, Anytown, USA",
    },
    {
      id: 10,
      name: "John Glover",
      students: ["Stella Scott"],
      email: "mike@geller.com",
      phone: "1234567890",
      address: "123 Main St, Anytown, USA",
    },
  ];
  
  export const subjectsData = [
    {
      id: 1,
      name: "Math",
      teachers: ["Alice Phelps", "Russell Davidson"],
    },
    {
      id: 2,
      name: "English",
      teachers: ["Manuel Becker", "Eddie Chavez"],
    },
    {
      id: 3,
      name: "Physics",
      teachers: ["Lola Newman", "Darrell Delgado"],
    },
    {
      id: 4,
      name: "Chemistry",
      teachers: ["Nathan Kelly", "Benjamin Snyder"],
    },
    {
      id: 5,
      name: "Biology",
      teachers: ["Alma Benson", "Lina Collier"],
    },
    {
      id: 6,
      name: "History",
      teachers: ["Hannah Bowman", "Betty Obrien"],
    },
    {
      id: 7,
      name: "Geography",
      teachers: ["Lora French", "Sue Brady"],
    },
    {
      id: 8,
      name: "Art",
      teachers: ["Harriet Alvarado", "Mayme Keller"],
    },
    {
      id: 9,
      name: "Music",
      teachers: ["Gertrude Roy", "Rosa Singleton"],
    },
    {
      id: 10,
      name: "Literature",
      teachers: ["Effie Lynch", "Brett Flowers"],
    },
  ];